package com.androidforever.rprccontroller.app;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.androidforever.rprccontroller.app.Host;

import com.androidforever.rprccontroller.app.HostDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig hostDaoConfig;

    private final HostDao hostDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        hostDaoConfig = daoConfigMap.get(HostDao.class).clone();
        hostDaoConfig.initIdentityScope(type);

        hostDao = new HostDao(hostDaoConfig, this);

        registerDao(Host.class, hostDao);
    }
    
    public void clear() {
        hostDaoConfig.getIdentityScope().clear();
    }

    public HostDao getHostDao() {
        return hostDao;
    }

}
