package com.androidforever.rprccontroller.app;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.androidforever.rprccontroller.app.Host;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table HOST.
*/
public class HostDao extends AbstractDao<Host, String> {

    public static final String TABLENAME = "HOST";

    /**
     * Properties of entity Host.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Host = new Property(0, String.class, "host", true, "HOST");
    };


    public HostDao(DaoConfig config) {
        super(config);
    }
    
    public HostDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'HOST' (" + //
                "'HOST' TEXT PRIMARY KEY NOT NULL );"); // 0: host
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'HOST'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Host entity) {
        stmt.clearBindings();
 
        String host = entity.getHost();
        if (host != null) {
            stmt.bindString(1, host);
        }
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Host readEntity(Cursor cursor, int offset) {
        Host entity = new Host( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0) // host
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Host entity, int offset) {
        entity.setHost(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(Host entity, long rowId) {
        return entity.getHost();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(Host entity) {
        if(entity != null) {
            return entity.getHost();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
