package com.androidforever.rprccontroller.app;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import java.net.InetAddress;
import java.util.ArrayList;
import java.util.List;
// KEEP INCLUDES END


/**
 * Entity mapped to table HOST.
 */
public class Host {

    private String host;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Host() {
    }

    public Host(String host) {
        this.host = host;
    }

    public String getHost() {
        return host;
    }

    public void setHost(String host) {
        this.host = host;
    }

    // KEEP METHODS - put your custom methods here

    public static List<Host> fromInetAddressList(List<InetAddress> inetAddresses)
    {
        List<Host> hosts = new ArrayList<>();
        for(InetAddress addr : inetAddresses)
        {
            hosts.add(new Host(addr.getHostAddress()));
        }
        return hosts;
    }

    @Override
    public String toString()
    {
        return host;
    }

    @Override
    public boolean equals(Object o)
    {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Host host1 = (Host) o;

        return !(host != null ? !host.equals(host1.host) : host1.host != null);

    }

    @Override
    public int hashCode()
    {
        return host != null ? host.hashCode() : 0;
    }

    // KEEP METHODS END

}
